-- Import Category, Genre, Country from Website PL Data Final.csv
-- Columns used: B=ID, C=Title, D=Category, E=Genre, F=Account, G=Master, S=Country

ALTER TABLE ads_playlist_settings
  ADD COLUMN IF NOT EXISTS playlist_id TEXT,
  ADD COLUMN IF NOT EXISTS playlist_name TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS genre TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS account_name TEXT,
  ADD COLUMN IF NOT EXISTS master_playlist TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS ads_playlist_settings_playlist_id_key
ON ads_playlist_settings (playlist_id);

INSERT INTO ads_playlist_settings
  (playlist_id, playlist_name, category, genre, country, account_name, master_playlist, updated_at)
VALUES
  ('0OimUfM688YTJbgTTYIdxi', 'INTENSA Running 180–190 BPM 🔥 Música para Correr Rápido | Playlist Jogging', 'Running', 'World EDM', 'Spain', 'Arthur LeGrand', 'World EDM Spanish', NOW()),
  ('3XW1EIKjIdbQV6w5LCCcN1', 'INTENSE Running Music 180–190 BPM 🔥 Fast Songs for Running | High Tempo Jogging Playlist', 'Running', 'Techno', 'United Kingdom', 'Arthur LeGrand', 'Techno 150-170', NOW()),
  ('1LziVsQzasZGTaDTeljPuH', 'Running 180 BPM À FOND 🔥 | Musique Rapide pour Sport | Playlist Jogging', 'Running', 'World EDM', 'France', 'Arthur LeGrand', 'World EDM French', NOW()),
  ('4HQDclD6nbheMyk5bRP6Zf', 'BRUTAL Running 150–160 BPM 🔥 Música Running 150–160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'Spain', 'Arthur LeGrand', 'World EDM Spanish', NOW()),
  ('651v5G7oEwoHQds973GEmX', 'Músicas para Aula de Spinning 2026 | Treino de Bike Indoor, Pop & EDM Energético 🚴‍♂️🎶', 'Spinning', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM Portuguese', NOW()),
  ('3hg5OBVSyRBEUZxolAYNFl', 'EDM Club Bangers 2026 | Party Anthems, House Hits & Gym House 🔥🕺', 'EDM', 'Techno', 'Germany', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('7EZurUdpzoFuFOPBOA49HV', 'BRUTAL 160-170 BPM Ciclismo 2026 🔥 Playlist Spinning Indoor | Música Cardio Energética', 'Spinning', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM Spanish', NOW()),
  ('0d5wo3ZmbnrDi83CSiiBa9', 'KRACHTIG Hardlopen 150–160 BPM 🔥 Running Muziek 150–160 BPM | Tempo Cardio Run Playlist', 'Running', 'World EDM', 'Netherlands', 'Arthur LeGrand', 'World EDM Netherlands', NOW()),
  ('3NbkCqtMk9SOFbfQcAZS2X', 'KRÄFTIG Cycling Mix 150-160 BPM 🔥 Indoor Spinning Playlist | Energiegeladene Cardio Musik', 'Spinning', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM German', NOW()),
  ('28eKAWVCjQEz7BvJ4jDwS9', 'Running Music 200 BPM | Super Fast Songs for Running & Extreme Speed Workouts ⚡🏃‍♂️', 'Running', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno 150-170', NOW()),
  ('0jMj25awEUk8r96EQ6Flaz', 'SCHNELLE Running 150–160 BPM 🔥 Laufmusik 150–160 BPM | Tempo Run Playlist | Cardio Songs', 'Running', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM German', NOW()),
  ('641VsCtWb3iEJ50ei2hrsi', 'Gym Bangers 2026 | Hard Workout Hits, High Energy & Training Motivation 🔥💥', 'Workout', 'Techno', 'Spain', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('3v68aBUy2LBHIfngDuOaif', 'PAZZESCA Corsa 180–190 BPM 🔥 Musica per Correre Veloce | Playlist Jogging', 'Running', 'World EDM', 'Italy', 'Arthur LeGrand', 'World EDM Italian', NOW()),
  ('6B168nmKMp12ceaTPFPJ7U', 'WUCHTIGER Laufmusik 180–190 BPM 🔥 Schnelle Songs fürs Running | High Tempo Jogging Playlist', 'Running', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM German', NOW()),
  ('5Z6VJV31v0RKpG4gUfm353', 'POTENTE Corsa 150–160 BPM 🔥 Musica Running 150–160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'Italy', 'Arthur LeGrand', 'World EDM Italian', NOW()),
  ('1BnkEG5sBSK4qUNCXR9EU6', 'INSANE Running 150–160 BPM 🔥 150–160 BPM Running Music | Tempo Run Playlist | Cardio Training Songs', 'Running', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno 150-170', NOW()),
  ('7kL6pZJjgroakclJmbLUDz', 'Druid Meditation | Celtic Ambient, Forest Ritual Sounds 2026 💎🌿', 'Meditation', 'Ambient', 'Australia', 'Arthur LeGrand', 'Ambient Druid', NOW()),
  ('3iRWGxDEoxPCLs6CDuCaK6', 'Gymrat 2026 | Hardcore Workout Music, Gym Motivation & Beast Mode 💥🌌', 'Workout', 'Techno', 'Germany', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('6MFxDgRKXYZH3KxTNEpsHl', 'Gym Temazos 2026 | Éxitos Energéticos, Motivación & Canciones para Cardio 🔥💥', 'Workout', 'World EDM', 'Spain', 'Arthur LeGrand', 'World EDM Spanish', NOW()),
  ('0r4ZUOVjd0w1uhoa5mZdIz', 'MÉGA Running 150–160 BPM 🔥 Musique Running 150–160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'France', 'Arthur LeGrand', 'World EDM French', NOW()),
  ('3efTWk4Zs5y1BsvfcjNfd0', 'Upbeat Pop Songs 2026 | Feel-Good Pop Hits & Happy Music ☀️🎶', 'Pop', 'Pop', 'United Kingdom', 'Arthur LeGrand', 'Pop', NOW()),
  ('3IdMMEysbfQ3IUD9a1pwJJ', 'Rowing Machine Songs 2026 | Rowing Workout Music, Cardio & Power Training 🎶💪', 'Workout', 'Techno', 'Spain', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('3OIEK5FH9vEekTQCe0Iu6c', 'EXTREME Hardlopen 180–190 BPM 🔥 Snelle Running Muziek | Jogging Playlist', 'Running', 'World EDM', 'Mexico', 'Arthur LeGrand', 'World EDM Netherlands', NOW()),
  ('1YQJfnMgKGfZKZmFnJN8nK', 'Shaolin Meditation | Zen Focus, Martial Arts Calm, Deep Inner Balance 2026 🧘‍♀️', 'Meditation', 'Ambient', 'Mexico', 'Arthur LeGrand', 'Ambient Eastern', NOW()),
  ('0XykLO3UBIsv12h5MUFgwX', 'Techno Mix 2026 | Rave Techno Remixes, Hard Beats, Party Gym & Car Music 🧪⚡', 'Techno', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('0TB2sckC3glHGD9cgoRNna', 'Cleanse Home & Body from Negative Energy | Healing Frequency Music 2026 🏋️😴', 'Meditation', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('2b43FAF1QWpk55k06MEZ1Z', 'SOOTHING Sleep for Overthinkers 🌙 | Quiet Mind & Deep Sleep Music', 'Sleep', 'Ambient', 'Australia', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('5NGL7eGt7jkANT2raweVZP', 'Zumba Beats 2026 | Zumba Workout Music, Dance Fitness & High-Energy Hits 💃🔥', 'Workout', 'Techno', 'United Kingdom', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('4o0ifqaPQRd6Nkk61H9JKt', 'Bassline Bangers ⚡ | UK Bassline, Club Hits, Heavy Bass, Speed Garage, Party Anthems 🔊', 'UKG', 'Techno', 'Turkey', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('01ctcL3jlXrcv03hOw7IDA', 'Canzoni da Palestra 2026 🔥 Migliori Brani per Allenamento e Motivazione | Musica per la Palestra 💃', 'Workout', 'World Pop', 'United Kingdom', 'Arthur LeGrand', 'World Soft Italian', NOW()),
  ('58kG3TfazVtdXiEvHv0Jq2', 'DEEP Studying for Exams 📚 | Focus Music | Study Playlist | Concentration Tracks', 'Studying', 'Soft Pop', 'Brazil', 'Arthur LeGrand', 'Soft Pop', NOW()),
  ('6iWD8vMkUkVivAD00wH4sF', 'Calming Sounds for Studying, Concentration, Relaxation, and Meditation | Focus & Peaceful Ambience 2', 'Studying', 'Ambient', 'Australia', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('3oattIb1HIHUAr4uphNpMW', '741 Hz Cortisol Detox | Anxiety & Stress Relief, Full Body & Mind Cleanse 2026 🕺 🛌', 'Meditation', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient 741 Hz', NOW()),
  ('4TNjgx7saNibtwNj8QpIlc', 'Sacred DRUID Meditation 🌿 | Celtic Forest Ambient & Ritual Atmosphere', 'Meditation', 'Ambient', 'Australia', 'Arthur LeGrand', 'Ambient Druid', NOW()),
  ('7FhcbimO328VlO4T1ycUCT', 'Songs for Rich People 2026 | Luxury Vibes, Money Music & Elite Energy 💸✨', 'Lounge', 'Mixed', 'Australia', 'Arthur LeGrand', 'Commercial Mix', NOW()),
  ('2DRV17IO3eYHq7CthMrbcd', 'Spinning Songs 150-160 BPM 2026 | Spinning Workout, Cycling Music & Spin Class 🚴‍♀️⚡', 'Spinning', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno 150-170', NOW()),
  ('3f3iOpvqurqINcgjCAEEgp', 'Deep Melodic House Vibes  | Melodic House & Techno, Deep House, Afterhours, Night Drive', 'Deep House', 'Chill House', 'Germany', 'Arthur LeGrand', 'Chill House', NOW()),
  ('13sq9Yid16Kbcv2Lu6qbVI', 'Gym House 2026 | House Beats for Workout, Fitness & Dance Energy ⚡💃', 'Workout', 'Techno', 'United Kingdom', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('3oGaNqXQ1ChJocZzZjE7DG', 'Speeding Bangers 2026 | Fast Dance Hits, High BPM & Adrenaline Music 💃⚡', 'Workout', 'Techno', 'United Kingdom', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('3WLWOsTaOfpaAqZybZh4Z3', 'Techno Mix 2026 | Rave Techno Remixes, Hard Techno, Peak-Time Energy for Party, Gym & Driving ⚡🔥', 'Techno', 'Techno', 'Germany', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('0VkEXHniyiN3V53k91nTaI', '10 Hours of Deep Sleep Music | Improve Sleep 2026 🎵💪', 'Sleep', 'Ambient', 'Brazil', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('4I0azrNdoqeuzx64WhMKvD', 'ADRENALINE Power Cycling 160 BPM 2026 ⚡ Indoor Spinning Playlist | High-Energy Cardio Music', 'Spinning', 'World EDM', 'Turkey', 'Arthur LeGrand', 'World EDM French', NOW()),
  ('3cfDxi2qYDBfufkbGDL0i8', 'Deep Ambient Journeys 💥🧠 | Cinematic Atmospheres, Focus Music, Expansive Sound Design 2026 🌌', 'Studying', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('67mdwMVu3ZA3r7eXrHvUD4', 'Indoor Cycling 150 BPM 2026 | Spin Class Music, High Energy Cardio & Bike Workout 🚲🔥', 'Spinning', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno 140-150', NOW()),
  ('59IMOdaJRK3hQa2jtHoUQt', 'INTENSE Cours de SPINNING 160 BPM 🔥 Playlist Spinning Indoor | Musique Cardio Énergique', 'Spinning', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM French', NOW()),
  ('4u5lK8uunFg2G18eb87fcK', 'MAXIMALES Lernen für Prüfungen 📚 | Fokus Musik | Study Playlist | Konzentrationsmusik', 'Studying', 'World Pop', 'Switzerland', 'Arthur LeGrand', 'World Soft German', NOW()),
  ('3tNqsQ3eQpovvgWmMfnVhL', 'Theta Waves | Binaural Beats, Theta Frequencies for Deep Relaxation 2026 📚✨', 'Meditation', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('5x0ObIoVtv3EPgJ3x7hAsO', '8 Hours of Sleep Music | Deep Rest & Relaxation 2026 🎉😌', 'Sleep', 'Ambient', 'Brazil', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('10XnJPy2mH7Av9p8FsEEM6', 'Aerobic Workout Music 2026 | Cardio Songs for Aerobics & Fitness Training 💪', 'Workout', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('1ZALgJJbiBS6ZzPGOL91l8', 'Clean Girl Shower 2026 | Fresh Vibes, Soft Pop & Clean Aesthetic Music 🚿🤍', 'Lounge', 'Pop', 'United Kingdom', 'Arthur LeGrand', 'Pop', NOW()),
  ('5h15OO7PHSni0heAU44Gq1', 'Dance Night 2026 | Club Hits, Party Music & Nightlife Vibes 💃🔥', 'EDM', 'Techno', 'Australia', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('0rRoacxw9IS0Omsl4j1oJE', 'Healing Music & Nature Sounds | Relaxation, Stress Relief, Peaceful Ambience 2026 🌿🎧', 'Meditation', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient General', NOW()),
  ('0GBWDlifynCW0OfGU0KaZJ', 'INTENSO Studio per Esami 📚 | Musica per Concentrazione | Playlist Studio', 'Studying', 'World Pop', 'Chile', 'Arthur LeGrand', 'World Soft Italian', NOW()),
  ('5GTe3JUNIBVxPNquv6kD6Q', 'MAXIMALE Spinning 160 BPM 🔥 Indoor Cycling Playlist | Energieke Cardio Muziek', 'Spinning', 'World EDM', 'Netherlands', 'Arthur LeGrand', 'World EDM Netherlands', NOW()),
  ('4tnTjbeH0WjkWTaTOAxpnY', 'POTENTE 160–165 Corsa Ritmica 💪 | Musica per Correre 160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'Germany', 'Arthur LeGrand', 'World EDM Italian', NOW()),
  ('0N93NsViNARrVKmstLdmUg', 'RAFFINATA Musica Ristorante di Lusso 🥂 | Playlist Cena | Musica di Sottofondo | Atmosfera Elegante', 'Lounge', 'World Pop', 'Brazil', 'Arthur LeGrand', 'World Soft Italian', NOW()),
  ('1XpOq6ygigtAgI2BHr6TP5', 'Techno Music for Life | Hard Techno, Melodic Techno, Rave Anthems, Underground Beats 2026 🖤☀️', 'Techno', 'Techno', 'Germany', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('4VGdqzzt7eDqq7XeZwURGQ', 'ELEGANTE Música Restaurante de Lujo 🥂 | Playlist Cena | Música de Fondo | Ambiente Sofisticado', 'Lounge', 'World Pop', 'Brazil', 'Arthur LeGrand', 'World Soft Spanish', NOW()),
  ('6gCCnHlKyQ8bE9Wwl2EdAX', 'EXKLUSIVE Luxus Restaurant Musik 🥂 | Dinner Playlist | Hintergrundmusik | Elegante Stimmung', 'Lounge', 'World Pop', 'Germany', 'Arthur LeGrand', 'World Soft German', NOW()),
  ('7J7pQUgw7uMo99sNRIKDVs', 'MÁXIMA Estudiando para Exámenes 📚 | Música Focus | Playlist Estudio | Música Concentración', 'Studying', 'World Pop', 'Singapore', 'Arthur LeGrand', 'World Soft Spanish', NOW()),
  ('2jxehQFsAmztMo6ifDnTxs', 'Workout 2026 | High Energy Exercise Music, Cardio Playlist & Dance Hits 🔥💪', 'Workout', 'Techno', 'Australia', 'Arthur LeGrand', 'Techno Main', NOW()),
  ('0miYy2RTqz1T9JKi1hnVMG', 'UKG & GARAGE 🌴⚡ | Bassline Anthems, Club Bangers, UK Hits🔊', 'UKG', 'UKG', 'United Kingdom', 'Arthur LeGrand', 'UKG', NOW()),
  ('77uTOkQWZ8ndU1IZiyyFUr', 'UNREAL Strength Mix 140-150 BPM 🖤🔥 | Powerlifting Songs & Heavy Lifting', 'Workout', 'Techno', 'Mexico', 'Arthur LeGrand', 'Techno 140-150', NOW()),
  ('3WK4yg5FJqE9rZqjFwIVcY', 'GYM HOUSE 2026 💪 HOUSE MIX 🏋️ WORKOUT MOTIVATION', 'Workout', 'Techno', 'Mexico', 'Kim Kay', 'Techno Main', NOW()),
  ('4CtXsmUTGWpFGhNGYxb9ic', 'PILATES & CHILL 2026 ✨ PILATES FLOW 🌿 CHILL BEATS', 'Wellness', 'Mixed', 'Mexico', 'Kim Kay', 'Commercial Mix', NOW()),
  ('7b0g0LmwCbY3Lst0UwAocY', 'EHRENLOSE REMIXES 2026 🔥 KRASSE BASS REMIXES ⚡️ TIKTOK HITS', 'Remixes', 'World EDM', 'Germany', 'Kim Kay', 'World EDM German', NOW()),
  ('4PppwTQL5IEin89PGgrRa8', 'JUMP ROPE 150 BPM 2026 ⏱️ CARDIO BEATS 🔥 WORKOUT HITS', 'Workout', 'Techno', 'Spain', 'Kim Kay', 'Techno Main', NOW()),
  ('5vqWsqRPO3qQlFabcpvBmq', 'BEST INSTA STORY SONGS 2026 📱 TIKTOK VIRAL 🔥 TOP TRACKS', 'Viral', 'Viral Mixed', 'United Kingdom', 'Kim Kay', 'Viral Mixed', NOW()),
  ('0vrioIpruQojngSQBE8rdu', 'EXERCISE SONGS 130-150 BPM 2026 💦 CARDIO WORKOUT 💪 GYM MOTIVATION', 'Workout', 'Techno', 'Spain', 'Kim Kay', 'Techno 130-140', NOW()),
  ('2UvBAuWrwzSzb8PzUgCNt6', 'POP CHILL 2026 🕯 RELAXING HITS 🌿 CHILL POP SONGS', 'Lounge', 'Mixed', 'Australia', 'Kim Kay', 'Commercial Mix', NOW()),
  ('3r2lhwSFsiOvfHpmFEwraD', 'ASTRAL PROJECTION 2026 ✨ OUT OF BODY 🌌 BINAURAL BEATS', 'Meditation', 'Ambient', 'India', 'Kim Kay', 'Ambient General', NOW()),
  ('76HtMLhQFfepRlFwr1yKQC', 'RELAXING DRUMMING MEDITATION 2026 🥁 CALM VIBES 🌿 HEALING RHYTHMS', 'Meditation', 'Ambient', 'Mexico', 'Kim Kay', 'Ambient Percs', NOW()),
  ('6EkHz6MaQcvobOBTq5q1j8', 'RESTAURANT MUSIC 2026 🍷 SOFT POP 🌟 RELAXING HITS', 'Lounge', 'Soft Pop', 'Poland', 'Kim Kay', 'Soft Pop', NOW()),
  ('2As1rpvNBf5cwK9XlKBdxy', 'ZEN BUDDHISM MEDITATION 2026 🧘‍♂️ INNER PEACE 🌿 CALM FOCUS', 'Meditation', 'Ambient', 'United Kingdom', 'Kim Kay', 'Ambient General', NOW()),
  ('4o0ifqaPQRd6Nkk61H9JKt', 'Bassline Bangers ⚡ | UK Bassline, Club Hits, Heavy Bass, Speed Garage, Party Anthems 🔊', 'UKG', 'Techno', 'Turkey', 'Kim Kay', 'Techno Main', NOW()),
  ('3UAfKMQS5jjYr9Eo9qh15k', 'INDOOR Spinning & Outdoor CYCLING  160 BPM 2026 🚲 SPIN WORKOUT ⚡️ CYCLING HITS', 'Spinning', 'Techno', 'Mexico', 'Kim Kay', 'Techno Main', NOW()),
  ('0kcisooCdIAiej6J3N2xhI', 'AFRO HOUSE 2026 🌴 TEMAZOS 🎶 HITS PARA BAILAR', 'Afro House', 'Afro House', 'Greece', 'Kim Kay', 'Afro House', NOW()),
  ('2nU9ocH07AV3XAUbBwf24T', 'EPIC TikTok Mashups & Remixes 2026 🔥 – Sped Up, Slow Reverb & Viral Edits', 'Mashups', 'Mashups', 'Australia', 'Kim Kay', 'Mashups', NOW()),
  ('3ujniTOeTw389Pr0yqAMfc', 'YOGA INSTRUMENTAL MUSIC 2026 🌸 CHILL VIBES 🌿 RELAXING FLOW', 'Wellness', 'Instrumentals', 'United Kingdom', 'Kim Kay', 'Instrumentals', NOW()),
  ('4zENexAGzkYaETgRogMKQh', 'ADHD SLEEP MUSIC 2026 💤 CALMING SOUNDS 🌙 SLEEP THERAPY', 'Sleep', 'Ambient', 'Australia', 'Kim Kay', 'Ambient General', NOW()),
  ('3vNTcSdaRAasxp1wqelywJ', 'CLÁSICOS REMIXADOS 2026 🎶 FIESTA RETRO 🌟 VERSIONES ELECTRÓNICAS ICÓNICAS', 'Remixes', 'World EDM', 'Spain', 'Kim Kay', 'World EDM Spanish', NOW()),
  ('2h7tFQXIKeLKdSTPXewXhr', 'ÉPICOS Mashups & Remixes do TikTok 2026 🔥 – Áudios em Alta nos Reels', 'Mashups', 'Mashups', 'Thailand', 'Kim Kay', 'Mashups', NOW()),
  ('6Fzx9aQahLqi9QC39Y50Gg', 'PEACEFUL JAPANESE SLEEP MUSIC 😴 KOTO LULLABIES | SERENE VIBES', 'Sleep', 'Ambient', 'Singapore', 'Kim Kay', 'Ambient Eastern', NOW()),
  ('6WaN310mfMNBaIyL5zpKyE', 'RUNNING MUSIC 170 BPM 2026 🏃‍♂️ HIGH-TEMPO ⚡ FAST BPM WORKOUT', 'Running', 'Techno', 'Mexico', 'Kim Kay', 'Techno 150-170', NOW()),
  ('7ac0URBqfC4apmxb8OEGMb', 'TRIBAL BEATS 2026 | SHAMAN DRUMS 🌿 NATIVE FLUTES', 'Meditation', 'Ambient', 'Australia', 'Kim Kay', 'Ambient Percs', NOW()),
  ('6WA06xeA5UbI06o4QgtC7j', 'LUXURY HOTEL LOUNGE 2026 ✨ CHILLOUT 🎶 ELEGANT VIBES', 'Lounge', 'Pop', 'Brazil', 'Kim Kay', 'Pop', NOW()),
  ('4Q3hmH9dUCFzQ0BpgCfZhY', 'MORNING SONGS 2026 ☀️ COFFEE PLAYLIST ☕️ CHILL MORNING VIBES', 'Lounge', 'Soft Pop', 'Australia', 'Kim Kay', 'Soft Pop', NOW()),
  ('0VfOUmxAsdiM7oYqu79GEN', 'Sports Pump Up Music 2026 | Intense Training & Workout Hype Songs for Athletes and Motivation', 'Workout', 'Techno', 'Brazil', 'Kim Kay', 'Techno Main', NOW()),
  ('3UUFb7YQTE4OVm6ZNPBpq4', 'AGGRESSIVE BASS DROPS 140-150 BPM 2026 🔊 EDM FESTIVAL BANGERS', 'EDM', 'Techno', 'Chile', 'Kim Kay', 'Techno Main', NOW()),
  ('1qdMUrMKiEopU0lrtp7J8K', 'THETA WAVES 2026 ✨ BINAURAL BEATS 🌌 MEDITATION FREQUENCIES', 'Meditation', 'Ambient', 'India', 'Kim Kay', 'Ambient General', NOW()),
  ('46fOOGy5b5J4buNttN14VN', 'TREADMILL GYM 2026 👟 RUNNING BEATS ⚡ SPINNING WORKOUT MUSIC', 'Running', 'Techno', 'Mexico', 'Kim Kay', 'Techno Main', NOW()),
  ('2O6XeXNWLeX5l883AbWnsj', 'COOL DOWN POST-WORKOUT Recovery & Relaxed Energy 🌙✨', 'Workout', 'Mixed', 'Australia', 'Kim Kay', 'Commercial Mix', NOW()),
  ('45sln7xIgxB7BE30UocasN', 'MAD TikTok Viral Mashups 2026 🔥 – Trending Sounds & Hype Remixes', 'Mashups', 'Mashups', 'Brazil', 'Kim Kay', 'Mashups', NOW()),
  ('6RE0TlelSmcy0vJMVIAenH', 'TOP CARDIO FUSION 140 BPM 2026 💦 WORKOUT BEATS ⚡ BEST AEROBICS PLAYLIST', 'Workout', 'Techno', 'Germany', 'Kim Kay', 'Techno 140-150', NOW()),
  ('0FQStoL6nmjdxVTCuP31xQ', 'TOP UK GARAGE 2026 ⚡ SPEED GARAGE 🎶 BASSLINE & UKG', 'UKG', 'UKG', 'United Kingdom', 'Kim Kay', 'UKG', NOW()),
  ('3MdkigzmzXkDjXyGt4hMFN', 'UNHINGED Viral Mashups 2026 🔥 – TikTok & Instagram Trending Audio', 'Mashups', 'Mashups', 'Australia', 'Kim Kay', 'Mashups', NOW()),
  ('7ypUoUnQla3qCZ12JtMrpl', 'AMAZING Viral Remix Mashups 2026 🔥 – Social Media Party Hits', 'Mashups', 'Mashups', 'Thailand', 'Kim Kay', 'Mashups', NOW()),
  ('4azT1XKUUo5ava9GxiCi4O', 'BALANCE CHAKRAS WHILE SLEEPING ✨ HEALING FREQUENCIES 🕉️ AURA CLEANSING', 'Meditation', 'Ambient', 'India', 'Kim Kay', 'Ambient General', NOW()),
  ('0XCBGebzJtWCVjWgBq3SYW', 'BANHO RELAXANTE 2026 🛁 MÚSICA SUAVE 🌿 RELAX TOTAL', 'Wellness', 'World Pop', 'Australia', 'Kim Kay', 'World Soft Portuguese', NOW()),
  ('27owynNDpqUGkagr0CtmLK', 'BEST CAR MUSIC 2026 🚗 BASS BOOSTED 🔥 CAR DROPS', 'Driving', 'Techno', 'Germany', 'Kim Kay', 'Techno Main', NOW()),
  ('16VNfATtAvhdz2fpigNUZP', 'CRAZY Viral Mashups Nonstop 2026 🔥 – Trending Audio & FYP Mix', 'Mashups', 'Mashups', 'Brazil', 'Kim Kay', 'Mashups', NOW()),
  ('375Yy8vx7Gxy4HQyue0Nv7', 'DEEP SLEEP FREQUENCIES 9 CHAKRAS 🌙 ENERGY HEALING 🕉️ CALM REST', 'Meditation', 'Ambient', 'India', 'Kim Kay', 'Ambient General', NOW()),
  ('0WqoOP9RyT44W1xvI7G1qZ', 'EPIC TikTok Trending Mashups 2026 🔥 – Remix Edits & Party Energy', 'Mashups', 'Mashups', 'Australia', 'Kim Kay', 'Mashups', NOW()),
  ('3hy0SzQOw1dArHfi3Afegy', 'INSANE Viral Mashups 2026 🔥 – TikTok & Instagram Trending Audio', 'Mashups', 'Mashups', 'Australia', 'Kim Kay', 'Mashups', NOW()),
  ('24rb8g7ZjKOrJH3MQfaC3O', 'TRENDING TikTok Mashups 2026 🔥 – Viral Transitions & Party Edits', 'Mashups', 'Mashups', 'Brazil', 'Kim Kay', 'Mashups', NOW()),
  ('508IOoSYdvS0f9VtiDABsc', 'UNSTOPPABLE Viral Mashups Nonstop 2026 🔥 – Trending Audio & FYP Mix', 'Mashups', 'Mashups', 'Brazil', 'Kim Kay', 'Mashups', NOW()),
  ('1ctd74It4kIuf9iCjzn4LB', 'WILD TikTok Mashups 2026 🔥 – Sped Up, Slow Reverb & Viral Edits', 'Mashups', 'Mashups', 'Australia', 'Kim Kay', 'Mashups', NOW()),
  ('2LJTmT4QWHntCkmi8jNjw3', 'EXPLOSIVE TikTok Mashup Party Mix 2026 🔥 – Hype Songs & Remix Drops', 'Mashups', 'Mashups', 'Brazil', 'Kim Kay', 'Mashups', NOW()),
  ('1qqbf8p7OpG2qndH31pXfb', 'ICONIC Mashup Remix Hits 2026 🔥 – Viral Social Media Sounds', 'Mashups', 'Mashups', 'Thailand', 'Kim Kay', 'Mashups', NOW()),
  ('1CdTHP9tAG7XXHPZYPCmuE', 'Songs to Model Walk To | Fierce Runway Playlist | Confidence & Catwalk Energy🏋️', 'Aesthetic', 'Viral Mixed', 'Australia', 'Kim Kay', 'Viral Mixed', NOW()),
  ('3Jphym4vBDJbS3JSs3mJZY', 'INSANE Running 140–150 BPM 🔥 150–160 BPM Running Music | Tempo Run Playlist | Cardio Training Songs', 'Running', 'Techno', 'Germany', 'Titan Hawk', 'Techno 140-150', NOW()),
  ('1vBfepUhP5Dfg1Kt2JCyFl', 'INTENSE Running Music 170–180 BPM 🔥 Fast Songs for Running | High Tempo Jogging Playlist', 'Running', 'Techno', 'United Kingdom', 'Titan Hawk', 'Techno 150-170', NOW()),
  ('1wxNaGyVQ6hHn7gpOqop0u', 'Spinning Songs 150-160 BPM 2026 | Spinning Workout, Cycling Music & Spin Class 🚴‍♀️⚡', 'Spinning', 'Techno', 'Australia', 'Titan Hawk', 'Techno 150-170', NOW()),
  ('5iRfA6444JvAfNdgHBqH6y', 'EXTREMO Running 150–160 BPM 🔥 Música Running 150–160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'Mexico', 'Titan Hawk', 'World EDM Portuguese', NOW()),
  ('4obKtBe3ZgQI4YcHsKQHmn', 'Cool Down 2026 | Post-Workout Recovery & Relaxed Energy 🌙✨', 'Workout', 'Mixed', 'Chile', 'Titan Hawk', 'Commercial Mix', NOW()),
  ('4lz1ULTrHjfAF3jkYsv5fe', 'Stretching Workout 2026 | Flexibility, Recovery & Cool Down Music 🧘‍♀️✨', 'Workout', 'Mixed', 'Mexico', 'Titan Hawk', 'Commercial Mix', NOW()),
  ('4otn2YUP0D6er2yD0yDboz', 'JUMP ROPE 140 BPM 2026 ⏱️ CARDIO BEATS 🔥 WORKOUT HITS', 'Workout', 'Techno', 'Mexico', 'Titan Hawk', 'Techno 130-140', NOW()),
  ('0N70tbqKJPvGIGcVOlw5BP', 'Home Workout 2026 | Full Body Training & High-Energy Fitness 🔥🏠', 'Workout', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('0xJ2vKS7Nb7Le0ugC3VshF', 'Running Music 200 BPM | Super Fast Songs for Running & Extreme Speed Workouts ⚡🏃‍♂️', 'Running', 'Techno', 'United Kingdom', 'Titan Hawk', 'Techno 150-170', NOW()),
  ('1L9vgjx875rvvn0TbGwCN6', 'Abs Workout 2026 | Sixpack Training & Core Burn 🔥💦', 'Workout', 'Techno', 'Australia', 'Titan Hawk', 'Techno Main', NOW()),
  ('6KDttfiKSzbNJJaACQ22mc', 'EPIC EDM Summer 2026 Hits 🔥 | 140–150 BPM Festival Energy', 'EDM', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('75LeNKVCTVwyj294m5Op0D', 'INTENSE 160–165 Rhythmic Running 💪 | Fast Tempo Run Playlist | Cardio Training Songs', 'Running', 'Techno', 'Mexico', 'Titan Hawk', 'Techno 150-170', NOW()),
  ('75LhrvDp08ui1e2jGBpZlY', 'AFRICA BEATS 2026 🇿🇦🇳🇬 | Amapiano South Africa & Nigeria 🔥 | Dancehall & Afrobeats', 'Amapiano', 'Amapiano', 'Angola', 'Titan Hawk', 'Amapiano', NOW()),
  ('7ue0O7xuR3HoERLDcOGBpK', 'Cool Down 2026 | Post-Workout Recovery & Relaxed Energy 🌙✨', 'Workout', 'Mixed', 'Chile', 'Titan Hawk', 'Commercial Mix', NOW()),
  ('6PiUQdue5u3vChKv6NiO5e', 'Power Cycling 2026 | High-Intensity Bike Training Music 🚴‍♂️⚡', 'Spinning', 'Techno', 'Australia', 'Titan Hawk', 'Techno Main', NOW()),
  ('2YobhqIIbLoyNbQjTH9NBL', 'AFRICAN ROOTS 🌍🔥 | Jamaica, South Africa & Nigeria | Shell Down | Badman Riddim | Yard Vibes 🇯🇲🇿🇦🇳🇬', 'Riddim', 'Amapiano', 'Angola', 'Titan Hawk', 'Amapiano', NOW()),
  ('1kDvuqfbajL0YWZlTfwfev', 'GYM HOUSE 130-140 BPM 💪 HOUSE MIX 🏋️ WORKOUT MOTIVATION', 'Workout', 'Techno', 'United Kingdom', 'Titan Hawk', 'Techno 130-140', NOW()),
  ('68BzUytNVKBBnnmVKhDqdH', 'HIIT Training 2026 | High-Intensity Workout & Cardio Beats 🔥💪', 'Workout', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('3evztzgJdfpjxY3BEm3AAL', 'WEDDING Party Summer 2026 💍 | Crazy Celebration Vibes', 'Summer', 'Mixed', 'United Kingdom', 'Titan Hawk', 'Commercial Mix', NOW()),
  ('4uIsODhEyVmowZLgqmpxGm', 'Adrenaline Rush Workout 2026 | High-Intensity Training Beats ⚡🔥', 'Workout', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('32EBOwMX8SiNgM4wnHlfHF', 'Gym Temazos 150 BPM | Éxitos Energéticos, Motivación & Canciones para Cardio 🔥💥', 'Workout', 'World EDM', 'Germany', 'Titan Hawk', 'World EDM Portuguese', NOW()),
  ('2Yun0vIN9nBJfs5wqOAXYB', 'BRUTAL Running 150–160 BPM 🔥 Música Running 150–160 BPM | Playlist Tempo Run | Cardio', 'Running', 'World EDM', 'Spain', 'Titan Hawk', 'World EDM Spanish', NOW()),
  ('5dQAwVREGWctdK3vx88GpC', 'HARDCORE 170–180 BPM Outdoor Cardio Jogging 🔥 | High Tempo Workout Playlist', 'Running', 'Techno', 'Mexico', 'Titan Hawk', 'Techno 150-170', NOW()),
  ('1zEQkr6KKspW3utEX8S6wn', 'KRACHTIG Hardlopen 160-170 BPM 🔥 Running Muziek 160–170 BPM | Tempo Cardio Run Playlist', 'Running', 'World EDM', 'Netherlands', 'Titan Hawk', 'World EDM Netherlands', NOW()),
  ('2dJASLQSptOKMxj4HvlYEZ', 'AFRO BOUNCE 2026 | BADMAN RIDDIM | Afro Vibes | Dancehall Queen 🔥', 'Riddim', 'Amapiano', 'Angola', 'Titan Hawk', 'Amapiano', NOW()),
  ('1t28ivA7Ze8WnkqIKjYniA', 'Amapinao Riddim 2026 | Jamaican Dancehall | African Bashment Party 🔥', 'Amapiano', 'Amapiano', 'Angola', 'Titan Hawk', 'Amapiano', NOW()),
  ('3b50GDbYJW7WUpSVe3zLHK', 'BASHMENT Amapiano Party 2026 | AFRORIDDIM & AFROBEATS 🔥', 'Amapiano', 'Amapiano', 'Angola', 'Titan Hawk', 'Amapiano', NOW()),
  ('3GA5RHVkWtOOmtx3Jry0Sg', 'INTENSE Beach Workout 2026 🔥 | Summer Cardio & High Energy Training', 'Workout', 'Afro House', 'Australia', 'Titan Hawk', 'Afro House', NOW()),
  ('4MY3wU0sq8N7yPAceJl6P3', 'Interval Training — Beast Mode Tempo ⏱️🔥', 'Workout', 'Techno', 'United Kingdom', 'Titan Hawk', 'Techno Main', NOW()),
  ('13cCjAoOVeqonyew3xBDb7', 'Pilates & Hot Pilates 2026 | Core Strength, Conditioning & Flow 🔥🧘‍♀️', 'Workout', 'Mixed', 'United Kingdom', 'Titan Hawk', 'Commercial Mix', NOW()),
  ('5NVYZzH6H6zHxXxf4G6ZAz', 'Running Training — Beast Mode Beats 🏃‍♂️🔥', 'Running', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('650WB59YTZQ67xCW0BuLvR', 'HIIT Training — ADRENALINE Rush — Power & Intensity Beats 🔥⚡', 'Workout', 'Techno', 'Mexico', 'Titan Hawk', 'Techno Main', NOW()),
  ('0xVENjGczy6wn18c0mGwI5', 'WUCHTIGER Laufmusik 180–190 BPM 🔥 Schnelle Songs fürs Running | High Tempo Jogging Playlist', 'Running', 'World EDM', 'Germany', 'Titan Hawk', 'World EDM German', NOW()),
  ('3yiU4BHZz1Pf3DEyRAZ9fj', 'YOGA INSTRUMENTAL MUSIC 2026 🌸 CHILL VIBES 🌿 RELAXING FLOW', 'Wellness', 'Instrumentals', 'United Kingdom', 'Titan Hawk', 'Instrumentals', NOW()),
  ('4OMo8CEtedi2coDZVmxYJv', 'Sprint Training 2026 | Fast Running Music & Speed Work ⚡🏃‍♂️', 'Running', 'Techno', 'Australia', 'Titan Hawk', 'Techno Main', NOW()),
  ('3r8UDYNDFcjKgKYuqzmGw3', 'VIBRANT Island Vibes 🌊 | Island Hopping & Boat Life Energy', 'Beach', 'Afro House', 'United Kingdom', 'Titan Hawk', 'Afro House', NOW()),
  ('6LcancOhpGjazrN8v3uWBc', 'Techno Bass Boosted 2026 | Car Music Remixes, Heavy Bass, Driving Techno 🔥🚗', 'Techno', 'Techno', NULL, 'Arthur LeGrand', 'Techno Main', NOW()),
  ('1i9mVzyn5E6RHyACqiK2Ai', 'Sweet Reggae & Riddim 2010–2026 🌴🔥 | Reggae Hits, Dancehall, Island Vibes, Summer Classics ✨', 'Riddim', 'Reggae', 'Kenya', 'Arthur LeGrand', 'Reggae', NOW()),
  ('4D7MgcNzD0W55Wgr19zJqi', 'ADHD Techno | Hyperfocus Beats, Driving Techno, Deep Focus Energy 2026 🧠⚡', 'Techno', NULL, 'Germany', 'Arthur LeGrand', NULL, NOW()),
  ('1hFDnkX5L7n3dtnE8Nlq0j', 'BEACH WAVES @ NIGHT 🌊 | Ocean Ambience, Deep Sleep & Relaxation Sounds', 'Nature', NULL, 'United Kingdom', 'Arthur LeGrand', NULL, NOW()),
  ('0lnvvp78nfDwiVkHH2k9BT', 'Trending Praise & Worship 2026  | Gospel Hits, Worship Songs, Christian Praise, Viral Worship 🙏', 'Gospel', NULL, 'Nigeria', 'Arthur LeGrand', NULL, NOW()),
  ('6oGhBUaNe8cZL4Sdte4Qm5', 'Beatport Top 100 | Raw Techno, Deep Techno, Hypnotic Techno Charts 2026 🖤🔊', 'Techno', NULL, 'Germany', 'Arthur LeGrand', NULL, NOW()),
  ('3CbvuaGKRkZ5QfKLmaPIaZ', 'Beatport Top 100 | Tech House Charts, Club Anthems, Underground DJ Hits 2026 🎧🔥', 'EDM', NULL, 'Mexico', 'Arthur LeGrand', NULL, NOW()),
  ('47r8zSP6Oi902umYwNVv6f', 'Hype Classical Study Music  | High Energy Orchestra, Epic Instrumental Focus, Study Beats 2026', 'Studying', NULL, 'United Kingdom', 'Arthur LeGrand', NULL, NOW()),
  ('7KZZUb43PWcDGnESvhFxz3', 'Sleep Techno | Deep Minimal Techno, Hypnotic Beats, Night Focus & Calm Energy 2026 🌌🖤', 'Techno', NULL, 'Germany', 'Arthur LeGrand', NULL, NOW()),
  ('48VQvckWuJ3kgpsTv3QqYL', 'When My Spirit Is Weak  | Worship & Christian Songs, Faith, Healing, Prayer, Gospel Praise', 'Gospel', NULL, 'South Africa', 'Arthur LeGrand', NULL, NOW()),
  ('5XaXXlFmJfKo0lHYBbnibE', '528 Hertz Sleep & DNA Repair | Healing Frequency, Deep Relaxation, Meditation 2026 😴✨', 'Meditation', 'Ambient', 'India', 'Arthur LeGrand', 'Ambient 528 Hz', NOW()),
  ('157mfZc85ld92FAPNswQzm', 'Best Dub Techno Ever | Deep Dub Techno, Atmospheric Techno, Minimal & Hypnotic Beats 2026 🌫️🔊', 'Techno', NULL, 'Germany', 'Arthur LeGrand', NULL, NOW()),
  ('65jifFLC4I1TkrTdBAxyox', 'Relaxing Saxophone Vibes 🎷🍷 | Lounge Jazz, Chill Sax, Smooth Instrumentals, Coffee Shop Music ✨', 'Lounge', NULL, 'United Kingdom', 'Arthur LeGrand', NULL, NOW()),
  ('6l5lNX0jRV69Znykcp58oT', 'Beatport Top 100 | Peak Time Techno, Driving Techno, Festival & Club Anthems 2026 🖤⚡', 'Techno', NULL, 'Germany', 'Arthur LeGrand', NULL, NOW()),
  ('1sXtoKhyE0V2TVr1j6rNKR', 'AI COVERS OF FAMOUS SONGS 2026 | AI REMIX | VIRAL AI MUSIC | POPULAR HITS REIMAGINED', 'Remixes', NULL, 'Philippines', 'Kim Kay', NULL, NOW()),
  ('0Wn9w8KeUNvmlwb6vpi8mN', 'Classical Techno Music 2026🎻 Orchestral Rave | Symphonic Techno | Epic Classical Electronic playlist', 'Orchestral', NULL, 'Germany', 'Kim Kay', NULL, NOW()),
  ('6okroU3VKUgel9tXzro2hq', 'Dark Romance – Toxic Love & Obsessive Vibes', 'Romance', NULL, 'United Kingdom', 'Kim Kay', NULL, NOW()),
  ('4kAG5A3Qy5lSi1IPbQM5wp', 'Chill Soul Vibes 🥂 | Smooth Soul, Neo Soul & Chill R&B', 'Lounge', NULL, 'Thailand', 'Kim Kay', NULL, NOW()),
  ('2sRfIPSTBLZoaa1IHwTCTm', 'MÚSICA ÉPICA 2026 🐉 ORQUESTAL ⚔️ BATALLAS HEROICAS', 'Orchestral', NULL, 'United Kingdom', 'Kim Kay', NULL, NOW()),
  ('6fhjox82LDujbjYiqJVq33', 'CAR ENGINE SOUNDS 2026 🚗 VROOM VROOM ⚡ HIGH-SPEED TRACKS', 'Driving', NULL, 'Australia', 'Kim Kay', NULL, NOW()),
  ('4CHrIx3CG98P2wBbuGwZN3', 'CHANSONS POUR LES ENFANTS 2026 🇫🇷 🎵 TUNES AMUSANTES 🎵 FRENCH KIDS SONGS 2026 🇫🇷', 'Kids', NULL, 'France', 'Kim Kay', NULL, NOW()),
  ('6FD9ynYoynGAV2ucH9nzbJ', 'RAP LOVE SONGS 2026 💕 ROMANTIC HITS ❤️ HIP HOP BALLADS', 'Romance', NULL, 'Nigeria', 'Kim Kay', NULL, NOW()),
  ('0Qg61cV1AaUkBG3S75W5tw', 'Depressing Songs for the Boys - Sad Boy Hours & Heartbreak', 'Sad', NULL, 'United States', 'Kim Kay', NULL, NOW()),
  ('39CauoQWyTJAtG2n7bzs8y', 'Most Beautiful Orchestra Pieces 🎻 | Classical Masterpieces & Epic Scores', 'Orchestral', NULL, 'Mexico', 'Kim Kay', NULL, NOW()),
  ('6MqJyxbdpiPz6zONBc1QhW', 'SAD VIOLIN 2026 🎻 EMOTIONAL CLASSICS 🌙 CALM INSTRUMENTALS', 'Instrumental', NULL, 'United Kingdom', 'Kim Kay', NULL, NOW()),
  ('2U5DdCkBytAOng0GOkLaAI', 'WINTER SLEEP MUSIC 2026 ❄️ COZY NIGHTS 🌙 DEEP RELAXATION', 'Sleep', NULL, 'Australia', 'Kim Kay', NULL, NOW()),
  ('1hwLKsOim9mJfDi1bK9q75', 'ANIME PHONK GYM 2026 🔥 MUSCLE HACKING 💪 ANIME LIFTS', 'Workout', NULL, 'Brazil', 'Kim Kay', NULL, NOW()),
  ('34i5Onp05GNMOLGKoGxbrl', 'FREAKY Bedroom jams 🥵😈💦 Freaky Playlist • Naughty Music 😏👅💦', 'Romance', NULL, 'Australia', 'Kim Kay', NULL, NOW()),
  ('52JwAPGr5KhxlVM5R5l8Ou', 'Liminal Space / Dreamcore | Surreal Ambient Music | Nostalgic & Eerie Vibes', 'Aesthetic', NULL, 'Mexico', 'Kim Kay', NULL, NOW()),
  ('4qsBpHA92nP3xrsRtX4xxI', 'Jamaican WYFL Riddim 🇯🇲 | Dancehall Bashment Vibes | Amapiano 2026 🔥', 'Riddim', NULL, 'United Kingdom', 'Titan Hawk', NULL, NOW()),
  ('5TVigC8HCUBTJYUG2k6tjp', 'BREEZY Summer Hiking 🌿 | Nature Walk Escape Vibes', 'Walking', 'Chill House', 'United Kingdom', 'Titan Hawk', 'Chill House', NOW()),
  ('5JZkaSR2VOW0Dpi9i8I9ug', 'ADRENALINICO Mix Ciclismo 2026 🔥 Playlist Spinning Indoor | Musica Cardio Energica', 'Spinning', 'World EDM', NULL, 'Arthur LeGrand', 'World EDM Italian', NOW()),
  ('2wQFTwvqOxxKo9q5pn61wG', 'Hard Techno 2026 | Bangers Only, Rave Energy & Peak-Time Beats 🔥💃', 'Techno', 'Techno', NULL, 'Arthur LeGrand', 'Techno Main', NOW()),
  ('139nsBLwLbCRItoTTBLDDF', 'Pure Adrenaline 🏋️⚡ | Techno & Hard Techno, Rave Energy, Workout & Peak Focus 🔊', 'Workout', 'Techno', NULL, 'Arthur LeGrand', 'Techno Main', NOW()),
  ('4JgsrkH6NwiSDveDldF359', 'Techno Summer Ibiza | Ibiza Techno, Beach Raves, Sunset Club Anthems 2026 ☀️🏝️', 'Techno', 'Techno', NULL, 'Arthur LeGrand', 'Techno Main', NOW()),
  ('5EPuoLttPoC7SbVN4nXATu', 'ADHD Sleep Music features calming ambient tones, soft soundscapes, and gentle background music desig', 'Sleep', 'Ambient', NULL, 'Arthur LeGrand', 'Ambient General', NOW()),
  ('1DuMJZsuZ0DGT4xFKj8CQO', 'SAVAGE BADDY Workout 2026 🍑💪 | Hot Gym Girly & Fitness Motivation', 'Workout', 'Techno', NULL, 'Arthur LeGrand', 'Techno Main', NOW()),
  ('6YWX5ByctWFb2nsQaY6r3G', 'ZUMBA BEATS 140-150 BPM 2026 💃 ZUMBA WORKOUT 🔥 FITNESS DANCE MIX', 'Workout', 'Techno', NULL, 'Kim Kay', 'Techno Main', NOW()),
  ('6lE7jjOd6f8rXQq8qtjZKH', 'Street Racing Vibes | Night Drive Music | Bass Boosted Car Playlist | High Speed Energy🎵', 'Driving', 'Techno', NULL, 'Kim Kay', 'Techno Main', NOW()),
  ('1aJPXIpbzt9XeyulTir5n1', 'AMAZING Mashups 2026 🔥 – Viral Sounds & Edit Transitions', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('3C9xPNfyRXt66BV4r8tNNM', 'GOATED Viral Mashups 2026 🔥 – FYP Remix & Trending Sounds', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('3wEu10XQfI1dDqzSCXqy6r', 'INSANE Mashup Songs 2026 🔥 – Viral Audio, Remix Drops & Edit Mix', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('2b6B54oIPdae1Y4gZyDmat', 'LEGENDARY Mashup Songs 2026 🔥 – Viral Remix Compilation & Transitions', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('6i5S2ZyIkG2o295NMTAwKs', 'LEGENDARY Trending Mashups 2026 🔥 – Edit Culture & Viral Transitions', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('4cshCFrDinD0sVSbXfUE1T', 'UNREAL Mashup Songs 2026 🔥 – Viral Audio, Remix Drops & Edit Mix', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('1VvyQrMfqRNx2Ooiop0Xp5', 'LENDÁRIAS Mashup Songs 2026 🔥 – Compilação de Remixes Virais & Transições', 'Mashups', 'Mashups', NULL, 'Kim Kay', 'Mashups', NOW()),
  ('3LVRUkstxaGPgRfIRSBMtp', 'BRABO Running Music 180–190 BPM 🔥 Músicas Rápidas para Correr | Playlist Jogging', 'Running', 'World EDM', NULL, 'Titan Hawk', 'World EDM Portuguese', NOW()),
  ('2bf1OroMkBxN6tPDRKMdZ3', 'Ultra Marathon & Triathlon 2026 | Endurance, Stamina & Beast Mode Conditioning 🏔️🔥', 'Running', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('5IYReui4r4iIBshey6qcRP', 'ADRENALÍNICO Mix Ciclismo 2026 🔥 Playlist Spinning Indoor | Música Cardio Energética', 'Spinning', 'World EDM', NULL, 'Titan Hawk', 'World EDM Portuguese', NOW()),
  ('2O7NX5trzmuXKIqwicjMXG', 'Boxing Training — Beast Mode Power Mix 🥊🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('5ljz10MQL5ptANtFEvLDue', 'Pull Ups & Push Ups 2026 | Bodyweight Strength & Burn 🔥💪', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('6YWX5ByctWFb2nsQaY6r3G', 'ZUMBA BEATS 140-150 BPM 2026 💃 ZUMBA WORKOUT 🔥 FITNESS DANCE MIX', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('49KpeeDLUfgDn9QlVaq0jU', 'ADRÉNALINE 160–165 Running Rythmique 💪 | Musique Running 160 BPM | Playlist Tempo Run | Cardio', 'Running', 'Techno', NULL, 'Titan Hawk', 'Techno 150-170', NOW()),
  ('1YrcLbAYOGvSvRi3Aj8h5R', 'Boxing & Kickboxing Training 2026 | Conditioning, Power & Beast Mode Intensity 🥊🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('0UiUlmrpADp1mPg4b0p2rz', 'Burpees & Lunges 2026 | Cardio Strength & Fat Burn 🔥💦', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('6iMu2y83ZBUhzJV7RLYiR8', 'Circuit Training — Power & Adrenaline Mix 🔄🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('7bjFZfRI42qHT3iziGKcGb', 'Jump Rope & Rowing 2026 | Cardio Burn & Endurance Sweat 🔥🚣', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('766aHM66AeWCEhe8TbawjJ', 'Military Workout Training — Intensity & Power 🎖️🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('4wUNrPwfimRXUhWJvyY1Lr', 'Mountain Biking 2026 | Power, Endurance & High-Intensity Conditioning 🚵🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('54Zep2FUd5gnsEtWNPhzN5', 'BILLIONAIRE Summer 💎 | Alpha Quiet Flex Energy | Luxury Lifestyle', 'Summer', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('6JhBUMvFqZCuVekddkZgB3', 'Cycling Training — No Excuses Pump Up 🚴‍♂️🔥', 'Spinning', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('0KWBcjZm29itD5OfTbEmjT', 'ELITE Summer Vibes 140-150 BPM 🌞 | Summer Anthems Collection', 'Summer', 'Techno', NULL, 'Titan Hawk', 'Techno 140-150', NOW()),
  ('1nv37y7ebiEMy52ml8klVt', 'INTIMATE Summer Romance 💛 | Summer Aesthetic Vibes', 'Romance', 'Pop', NULL, 'Titan Hawk', 'Pop', NOW()),
  ('6hOHKvLsUvxJvMxD8vkGwB', 'SPLASHY Pool Party 🍹 | Poolside Cocktails & Summer Vibes', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('4aqyXIhXPXBq1ohukUP0Ca', 'AMAPIANO Beach Bar 🌴 | Island Chill & Sunset Vibes | Jamaica', 'Amapiano', 'Amapiano', NULL, 'Titan Hawk', 'Amapiano', NOW()),
  ('12ZcMGTFybpSbvtTCKyKSv', 'Animal Flow Training 2026 | Bodyweight Strength, Mobility & Conditioning 🐾🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('0PrjcgNUkHhRsnxEvr8jIf', 'Bulking Season 2026 | Heavy Lifting, Resistance & Mass Gains 💪🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('2F0cWaLrVvT4Xlh3N7tpdC', 'CRAZY Beach Party 🏖️ | #BeachVibes & Max Rizz Energy ☀️', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('6amsi1U34GwlvVD4vwQ5UR', 'CRAZY Pre-Beach Pump 150–160 BPM 🔥 | Gym Hype & Beach Body Energy', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno 150-170', NOW()),
  ('0MxmltpIjYhDVEjsJ0yzrh', 'E11EVEN, Omnia & Pacha Vibes | EPIC Global Club Anthems 🔥', 'EDM', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('3ged6cCLtzu1jXwAv9BcJp', 'ELITE Villa Weekend 🌴 | Summer Vibes, Pool & BBQ Energy', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('5q4J1inAvJvM2h2WWIgle9', 'GOLDEN Summer Sunset Vibes 🌅 | Beach Bonfire Nights', 'Summer', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('6xjkejGP7rIMzTUkC5J04j', 'ICONIC Bondi Beach Summer Party Vibes 🇦🇺 | #Australia Energy', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('1uKYO2DRtdnb3RCHHpltMe', 'ICONIC Tanning & Sun-Kissed Vibes ☀️ | Summer Glow Playlist', 'Beach', 'Mixed', NULL, 'Titan Hawk', 'Commercial Mix', NOW()),
  ('7A7121mGYNC4uYEPpaQejI', 'ICONIC Wine & Sunshine 🍷 | Summer Beach Drinking Playlist', 'Beach', 'Mixed', NULL, 'Titan Hawk', 'Commercial Mix', NOW()),
  ('4Kdrhmt96yhMof1B0TBMjs', 'LAVISH Yacht Party 🛥️ | Boat Party, Tanning & Champagne Vibes', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('336DKqV3rkD0Ly6S4DnlH0', 'MIAMI Night Energy 🌴 | Mar-a-Lago Club & LIV Vibes', 'EDM', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('3aRbQh2etD8umVcDjKtjzh', 'Military Workout 2026 | Strength, Stamina & No Excuses Intensity 🎖️🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('19Gv1XgzFibVDIKXLZUH0P', 'ROSÉ All Day 🍷 | ICONIC Party All Night #SummerVibes', 'Beach', 'Mixed', NULL, 'Titan Hawk', 'Commercial Mix', NOW()),
  ('2OLkQIMqgoDso4yi4YOR8r', 'Rowing Training — Stamina & Power Tracks 🚣🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('7FmI8Ra3E0RCpWzWtM7UMx', 'SALTY Hair Don’t Care 🌊 | Beach Sun Vibes Playlist ☀️', 'Beach', 'Mixed', NULL, 'Titan Hawk', 'Commercial Mix', NOW()),
  ('5KwfnwodjPBqv1BWKOPBtB', 'SAND In My TOES 👙 | Bikini Season Beach Vibes ☀️', 'Beach', 'Mixed', NULL, 'Titan Hawk', 'Commercial Mix', NOW()),
  ('3KkmldhYNLJBEaLUKe0qMv', 'SAVAGE Beach Running 160–170 BPM 🌊 | High Tempo Sand Run Playlist', 'Running', 'Techno', NULL, 'Titan Hawk', 'Techno 150-170', NOW()),
  ('6VAvQ8KL96mOWNywSbUF0P', 'Tactical Training — Adrenaline & Strength Music 🎯🔥', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('2PxSWgKDKUgczhcacJ7FjQ', 'TUFF Amapiano Afrobeats Riddim | Pon Di Floor | Afro Bashmen 🔥', 'Amapiano', 'Amapiano', NULL, 'Titan Hawk', 'Amapiano', NOW()),
  ('0yOJRWWsT7AkzO6xIG1OSk', 'ULTIMATE Beach Vibes 2026 🌴 | Summer Party & Chill Playlist', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('2VdMvkkc2JKhrzDNvqNeGi', 'VIBRANT Gold Coast Beach Vibes 🌊 | Australia Party Energy', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('2OmD3QOjz7WpLMURUy7jHl', 'VIBRANT Summer Vacation 🌴 | Summer Trips & #VacationMode', 'Summer', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW()),
  ('7adOKJ4QrndShoGcuLLrWq', 'EPIC Summer Shred 150–160 BPM 🔥 | Beach Body Energy Workout', 'Workout', 'Techno', NULL, 'Titan Hawk', 'Techno 150-170', NOW()),
  ('0oBc3ihmtnWVBgnfQjgLWr', 'Dreamy Vibes 2026 | Ethnic House, Melodic Techno, Minimal Techno, Chill Piano 🌙✨', 'EDM', 'Chill House', NULL, 'Arthur LeGrand', 'Chill House', NOW()),
  ('7yJioyPTyi1hxcQN6K861p', 'WALGESÄNGE 2026 🌊 SANFTE KLÄNGE 🐋 MEERESRUHE', 'Nature', NULL, NULL, 'Kim Kay', NULL, NOW()),
  ('0Af9A0s9Cfi8jeJsEYdOuN', 'ANGELIC Cover Songs ✨ | Soft Versions of Popular Hits', 'Instrumental', NULL, NULL, 'Kim Kay', NULL, NOW()),
  ('0fIn0LUjeuvOvMb4YUyVA3', 'Aura Songs  | Dark Pop, Mysterious Vibes, Aesthetic Energy', 'Aesthetic', NULL, NULL, 'Kim Kay', NULL, NOW()),
  ('1ZSThpeHJYzLLsMxsGslWC', 'Sad Girl Country  | Emotional Country Songs, Heartbreak Anthems', 'Country', NULL, NULL, 'Kim Kay', NULL, NOW()),
  ('2J7rezOGI9AkemChjyG2v2', 'CERTIFIED Mashup Transitions 2026 🔥 – Beat Drops & Viral Edits', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('0WxZyfGkYGXr17LxA8kwxq', 'CRAZY Trending Mashups 2026 🔥 – TikTok Trending Remixes', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('418b6bxyvGfUREM2w1sco8', 'CRAZY Viral Mashups 2026 ðŸ”¥ â€“ TikTok & Instagram Trending Audio', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('0uYnh6k5LrtwS1WYTmjwhb', 'DYNAMIC TikTok Trending Mashups 2026 🔥 – Remix Edits & Party Energy', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('2gIkxPZXUjHCairfidSbhK', 'EPIC Trending Mashups & Remixes 2026 🔥 – Viral Edit Audio Mix', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('5Ag2G4xdo7fq8IYm9dsafM', 'GOATED Mashups 2026 🔥 – FYP Songs, Viral Drops & Transition Mix', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('1X7ATqiEK5rWexOsSHA6MX', 'HYPER TikTok Mashups 2026 🔥 – Sped Up, Slow Reverb & Viral Edits', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('7BUzZUF8FUNV0hkaj5RkFI', 'INSANE Viral Mashups 2026 🔥 – TikTok Trending Sounds & Remixes', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('21NQDVdxXdTLDnMbIzcJHR', 'LOWKEY UNREAL Mashups 2026 🔥 – Viral Remix Compilation & Transitions', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('3qS2CNg2WJfG57au8L9jG4', 'MAIN CHARACTER Mashups 2026 🔥 – TikTok Trending Remixes', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('119xrATmgvxcimsNIadGtj', 'Mashup CORE Hits 2026 🔥 – Viral Social Media Sounds', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('7v5DJrB9p2BYdrlPDClEiu', 'NEXT LEVEL Viral Mashups 2026 🔥 – FYP Remix & Trending Sounds', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('5qrZ7Z77UfIOUeY6m9xmBF', 'OBSESSIVE TikTok Mashups 2026 🔥 – Trending Reels Audio', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('1GrBnYINbwxmOsa1uAAqpM', 'SAVAGE Trending Mashup Transitions 2026 🔥 – Beat Drops & Viral Edits', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('1g2stGKxh9NDnDMCJGODXC', 'UNREAL Viral Remix Mashups 2026 🔥 – Social Media Party Hits', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('0Gfr4xoaOvaDWPH9Gxp1s0', 'WILD TikTok Viral Mashups 2026 🔥 – Trending Sounds & Hype Remixes', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('6YunZqom1xq8Rid5g5HtCg', 'BLAZING Viral Mashups 2026 🔥 – TikTok Trending Sounds & Remixes', 'Category', 'Mashups', NULL, 'Kim Kay', NULL, NOW()),
  ('7lCZhWPCGDuxjhv4CT3WvI', 'BODRUM Beach Lifestyle ☀️ | Mediterranean Sun Vibes', 'Beach', 'Afro House', NULL, 'Titan Hawk', NULL, NOW()),
  ('3q23cPjz3HVpbYdInE2qFH', '100% Drip Rooftop Party 🥂 | Champagne & Sunset Flex', 'Summer', 'Afro House', NULL, 'Titan Hawk', NULL, NOW()),
  ('1kxtSG7JuZFYvYAXWC96JO', 'AMAZING Summer BBQ Playlist 🍔 | Backyard Party Vibes', 'Category', 'Afro House', NULL, 'Titan Hawk', NULL, NOW()),
  ('4W1OTU0SriM7eNgG3ZqzNf', 'Barbell Training 2026 | Squats, Deadlift & Bench Press Power 🏋️🔥', 'Category', 'Techno', NULL, 'Titan Hawk', NULL, NOW()),
  ('2tgePokAmihXWN1Pnk7ats', 'GLOW UP Energy & #SummerVibes | RADIANT Summer Vibes ✨', 'Summer', 'Mixed', NULL, 'Titan Hawk', NULL, NOW()),
  ('1dclCP90efdoFkCyYvdkyG', 'LEGENDARY Dubrovnik Coastal Vibes 🌊 | Adriatic Summer Energy', 'Beach', 'Afro House', NULL, 'Titan Hawk', NULL, NOW()),
  ('6YXtsPp7zWvj8fzDbT7axE', 'LEGENDARY Ushuaïa, Ocean Club & Nikki Beach Vibes | Beach Club Anthems 🌊', 'Beach', 'Afro House', NULL, 'Titan Hawk', NULL, NOW()),
  ('7bMBCSkggCW9vH6guc3MBH', 'NONCHALANT Summer Camping 🌄 | Summer Picnic Vibes', 'Summer', 'Mixed', NULL, 'Titan Hawk', NULL, NOW()),
  ('0QUoPovYYjbBHV8RQMukdN', 'Powerlifting Training — Power & Strain Mix 🖤🔥', 'Category', 'Techno', NULL, 'Titan Hawk', 'Techno Main', NOW()),
  ('2ryfO7PDyPMwfX5UidKU2e', 'WILD Ayia Napa Boat Party 🌊 | Mediterranean Summer Energy', 'Beach', 'Afro House', NULL, 'Titan Hawk', 'Afro House', NOW())
ON CONFLICT (playlist_id) DO UPDATE SET
  playlist_name = EXCLUDED.playlist_name,
  category = EXCLUDED.category,
  genre = EXCLUDED.genre,
  country = EXCLUDED.country,
  account_name = EXCLUDED.account_name,
  master_playlist = EXCLUDED.master_playlist,
  updated_at = NOW();

-- Verify import
SELECT playlist_id, playlist_name, category, genre, country, account_name, master_playlist, updated_at
FROM ads_playlist_settings
ORDER BY updated_at DESC
LIMIT 50;