name: Daily Playwright Auto Sync

on:
  schedule:
    - cron: "0 7 * * *" # 10:00 AM Beirut time during summer
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check Node install
        run: |
          node --version
          npm --version
          npx --version

      - name: Clean old installed modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Playwright
        run: |
          npm install --save-dev @playwright/test
          node ./node_modules/playwright/cli.js install --with-deps chromium

      - name: Run website auto sync
        run: node ./node_modules/@playwright/test/cli.js test tests/auto-sync.spec.ts --project=chromium
        env:
          AUTO_SYNC_URL: ${{ secrets.AUTO_SYNC_URL }}
          AUTO_SYNC_USERNAME: ${{ secrets.AUTO_SYNC_USERNAME }}
          AUTO_SYNC_PASSWORD: ${{ secrets.AUTO_SYNC_PASSWORD }}